# Generated by Django 3.2.5 on 2022-03-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataExpression',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local_timestamp', models.DateTimeField(auto_now=True)),
                ('object_url', models.URLField()),
                ('content_type', models.TextField()),
                ('content', models.FileField(upload_to='')),
                ('content_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddIndex(
            model_name='metadataexpression',
            index=models.Index(fields=['object_url'], name='trove_metad_object__5cf716_idx'),
        ),
        migrations.AddIndex(
            model_name='metadataexpression',
            index=models.Index(fields=['content_type', '-local_timestamp'], name='trove_metad_content_0616bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='metadataexpression',
            constraint=models.UniqueConstraint(fields=('content_hash',), name='metadata_expression__content_hash'),
        ),
    ]
