# Generated by Django 3.2.5 on 2022-03-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataExpression',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local_timestamp', models.DateTimeField(auto_now=True)),
                ('url_to_the_thing', models.URLField()),
                ('mediatype', models.TextField()),
                ('raw_expression', models.BinaryField()),
                ('hashed_expression', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddIndex(
            model_name='metadataexpression',
            index=models.Index(fields=['url_to_the_thing'], name='index_by_url_to_the_thing'),
        ),
        migrations.AddIndex(
            model_name='metadataexpression',
            index=models.Index(fields=['mediatype', '-local_timestamp'], name='index_by_recent_mediatype'),
        ),
        migrations.AddConstraint(
            model_name='metadataexpression',
            constraint=models.UniqueConstraint(fields=('hashed_expression',), name='unique_by_hashed_expression'),
        ),
    ]
