# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 14:22
from __future__ import unicode_literals

import db.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0019_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='throughawards',
            options={'verbose_name_plural': 'through awards'},
        ),
        migrations.AlterModelOptions(
            name='throughawardsversion',
            options={'verbose_name_plural': 'through awards'},
        ),
        migrations.AlterModelOptions(
            name='throughsubjects',
            options={'verbose_name_plural': 'through subjects'},
        ),
        migrations.AlterModelOptions(
            name='throughsubjectsversion',
            options={'verbose_name_plural': 'through subjects'},
        ),
        migrations.AlterModelOptions(
            name='throughtags',
            options={'verbose_name_plural': 'through tags'},
        ),
        migrations.AlterModelOptions(
            name='throughtagsversion',
            options={'verbose_name_plural': 'through tags'},
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractagent', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractagent',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_abstractagent_version', to='share.AbstractAgentVersion'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractagentrelation', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelation',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_abstractagentrelation_version', to='share.AbstractAgentRelationVersion'),
        ),
        migrations.AlterField(
            model_name='abstractagentrelationversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractagentrelationversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractagentversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractagentversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractagentworkrelation', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelation',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_abstractagentworkrelation_version', to='share.AbstractAgentWorkRelationVersion'),
        ),
        migrations.AlterField(
            model_name='abstractagentworkrelationversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractagentworkrelationversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractcreativework', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractcreativework',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_abstractcreativework_version', to='share.AbstractCreativeWorkVersion'),
        ),
        migrations.AlterField(
            model_name='abstractcreativeworkversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractcreativeworkversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractworkrelation', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelation',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_abstractworkrelation_version', to='share.AbstractWorkRelationVersion'),
        ),
        migrations.AlterField(
            model_name='abstractworkrelationversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_abstractworkrelationversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='agentidentifier',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_agentidentifier', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='agentidentifier',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_agentidentifier_version', to='share.AgentIdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='agentidentifierversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_agentidentifierversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='award',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_award', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='award',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_award_version', to='share.AwardVersion'),
        ),
        migrations.AlterField(
            model_name='awardversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_awardversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_extradata', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_extradata_version', to='share.ExtraDataVersion'),
        ),
        migrations.AlterField(
            model_name='extradataversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_extradataversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_tag', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_tag_version', to='share.TagVersion'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_tagversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughawards', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughawards',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_throughawards_version', to='share.ThroughAwardsVersion'),
        ),
        migrations.AlterField(
            model_name='throughawardsversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughawardsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughcontributor', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughcontributor',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_throughcontributor_version', to='share.ThroughContributorVersion'),
        ),
        migrations.AlterField(
            model_name='throughcontributorversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughcontributorversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughsubjects', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughsubjects',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_throughsubjects_version', to='share.ThroughSubjectsVersion'),
        ),
        migrations.AlterField(
            model_name='throughsubjectsversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughsubjectsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughtags', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='throughtags',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_throughtags_version', to='share.ThroughTagsVersion'),
        ),
        migrations.AlterField(
            model_name='throughtagsversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_throughtagsversion', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_workidentifier', to='share.Change'),
        ),
        migrations.AlterField(
            model_name='workidentifier',
            name='version',
            field=models.OneToOneField(editable=False, null=True, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='share_workidentifier_version', to='share.WorkIdentifierVersion'),
        ),
        migrations.AlterField(
            model_name='workidentifierversion',
            name='change',
            field=models.ForeignKey(editable=False, on_delete=db.deletion.DatabaseOnDelete(clause='CASCADE'), related_name='affected_workidentifierversion', to='share.Change'),
        ),
    ]
