# Generated by Django 3.2.5 on 2021-07-12 22:28

from django.db import migrations

import share.util.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0060_auto_20210712_1715'),
    ]

    operations = [
        migrations.RunPython(
            code=share.util.migrations.ensure_share_system_user,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=share.util.migrations.ensure_share_admin_user,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
