# Generated by Django 5.2.3 on 2026-06-05 13:26

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.operations
import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import share.models._old
import share.models.core
import share.models.fields
import share.models.source
import share.models.source_config
import share.models.validators
import share.util.migrations
import share.version


class Migration(migrations.Migration):

    # NOTE: when finishing the squash and deleting these other migrations, can also delete:
    # - share.models._old
    replaces = [
        ('share', '0001_squashed_0058_big_rend'),
        ('share', '0059_fmr_date_modified_index'),
        ('share', '0060_auto_20210712_1715'),
        ('share', '0061_ensure_auto_users'),
        ('share', '0062_indexbackfill'),
        ('share', '0063_featureflag'),
        ('share', '0064_drop_harvester_transformer_a'),
        ('share', '0065_drop_harvester_transformer_b'),
        ('share', '0066_drop_harvester_transformer_c'),
        ('share', '0069_rawdatum_mediatype'),
        # ('share', '0070_sourceuniqueidentifier_focus_identifier'),
        ('share', '0071_drop_ingestjob_regulatorlog'),
        ('share', '0072_indexbackfill_backfill_phase_index'),
        ('share', '0073_remove_indexbackfill_backfill_phase_index'),
        ('share', '0074_sourceuniqueidentifier_is_supplementary'),
        ('share', '0075_rawdatum_expiration_date'),
        ('share', '0076_rawdatum_share_rawdatum_expiration_idx'),
        ('share', '0077_big_cleanup_2025'),
        ('share', '0078_delete_rawdatum'),
    ]

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True, validators=[django.core.validators.MaxLengthValidator(64), django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(64)], verbose_name='first name')),
                ('last_name', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(64)], verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('gravatar', share.models.fields.ShareURLField(blank=True)),
                ('time_zone', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('locale', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_trusted', models.BooleanField(default=False, help_text='Designates whether the user can push directly into the db.', verbose_name='trusted')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('robot', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(40)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Share users',
                'verbose_name': 'Share user',
            },
            managers=[
                ('objects', share.models.core.ShareUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('color', models.IntegerField(choices=[(0, 'success'), (1, 'info'), (2, 'warning'), (3, 'danger')], default=1)),
                ('icon', models.CharField(blank=True, default='exclamation', max_length=31)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('long_title', models.TextField(unique=True)),
                ('home_page', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('is_deleted', models.BooleanField(default=False)),
                ('canonical', models.BooleanField(db_index=True, default=False)),
            ],
            managers=[
                ('objects', share.models.source.SourceManager()),
            ],
        ),
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('base_url', models.URLField(null=True)),
                ('transformer_key', models.TextField(null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_configs', to='share.source')),
            ],
            managers=[
                ('objects', share.models.source_config.SourceConfigManager()),
            ],
        ),
        migrations.CreateModel(
            name='SourceUniqueIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('source_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.sourceconfig')),
                ('is_supplementary', models.BooleanField(null=True)),
            ],
            options={
                'unique_together': {('identifier', 'source_config')},
            },
        ),
        migrations.CreateModel(
            name='CeleryTaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], db_index=True, default='PENDING', max_length=50)),
                ('task_id', models.UUIDField(db_index=True, unique=True)),
                ('meta', share.models.fields.DateTimeAwareJSONField(decoder=share.models.fields.DateTimeAwareJSONDecoder, editable=False, encoder=share.models.fields.DateTimeAwareJSONEncoder, null=True)),
                ('result', share.models.fields.DateTimeAwareJSONField(decoder=share.models.fields.DateTimeAwareJSONDecoder, editable=False, encoder=share.models.fields.DateTimeAwareJSONEncoder, null=True)),
                ('task_name', models.TextField(blank=True, db_index=True, editable=False, null=True)),
                ('traceback', models.TextField(blank=True, editable=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('share_version', models.TextField(default=share.version.get_shtrove_version, editable=False)),
            ],
            options={
                'verbose_name': 'Celery Task Result',
                'verbose_name_plural': 'Celery Task Results',
            },
        ),
        migrations.AddIndex(
            model_name='celerytaskresult',
            index=models.Index(fields=['-date_modified', '-id'], name='share_celer_date_mo_686d4d_idx'),
        ),
        migrations.CreateModel(
            name='IndexBackfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backfill_status', models.TextField(choices=[('initial', 'initial'), ('waiting', 'waiting'), ('scheduling', 'scheduling'), ('indexing', 'indexing'), ('complete', 'complete'), ('error', 'error')], default='initial')),
                ('index_strategy_name', models.TextField(unique=True)),
                ('specific_indexname', models.TextField()),
                ('error_type', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_context', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('is_up', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(
            code=share.util.migrations.ensure_share_system_user,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=share.util.migrations.ensure_share_admin_user,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
